spring:
  application:
    name: dormitory-allocation

  datasource:
    url: jdbc:postgresql://localhost:5432/dormitory_db
    username: dorm_user
    password: dorm_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG